Improve mqtt reliability
turmoni/ooler-mqtt-bridge pull request #7
Opened 2023-02-25 20:12 UTC by sredman

Re-jigger the background task creation to use a [TaskGroup](https://docs.python.org/3/library/asyncio-task.html#asyncio.TaskGroup) which seems to be the recommended way to wait on multiple tasks.

Using the new ability to wait on multiple tasks, add exception-catching and retries as suggested in the [asyncio-mqtt docs](https://pypi.org/project/asyncio-mqtt/#reconnecting).

Prior to these changes, I was having lots of trouble with MQTT losing connection. I added this retry handling to try to work around that, but somehow MQTT is now behaving correctly? I suspect it's unrelated, likely due to my [wifi signal strength](https://xkcd.com/1457/).

2023-10-21 17:55 UTC, turmoni commented
This is something I'd now be happy to merge after being rebased, since Python 3.11 has been out for long enough that I think most target platforms support it.

2023-10-22 01:15 UTC, sredman commented
Rebased

Don't get too excited, but I have a couple more PRs in branches which had dependencies on these changes and those in #3 
(Literally, do not get too excited. It's all about adding Fahrenheit control so I don't lose accuracy doing F -> C conversion...)

2023-11-03 00:47 UTC, turmoni commented
Thanks for the rebase, and sorry for taking a while to respond! I've now got this code running on my setup to verify it, just two comments:

- The double import of asyncio
- The extra `)` breaking the syntax

Apart from that it seems to be working fine for me, and I'll also look forward to gaining the Fahrenheit functionality

2023-11-03 00:49 UTC, turmoni requested changes
Ah whoops. I hadn't realised that just adding comments on the PR without submitting a review meant that the comments didn't go anywhere, sorry about that!

2023-11-03 00:49 UTC, turmoni commented on ooler_mqtt_bridge
> +import asyncio
Minor nitpick, we already have asyncio imported

2023-11-03 00:49 UTC, turmoni commented on ooler_mqtt_bridge
> +                async with asyncio.TaskGroup() as tg:
This is really new, as in "I run Arch and my version of Python doesn't have TaskGroup yet". I'm not sure which version of Python I want to target, but I'm afraid it'll probably have to be a little while before TaskGroup can be used more generally. Are there changes in this PR that are also useful applicable to not using a TaskGroup? I've not had MQTT connection issues myself, so I'm not sure what aspects are helpful.

2023-11-03 00:49 UTC, turmoni commented on ooler_mqtt_bridge
> +                password=config["mqtt_password"]) if "mqtt_password" in config else None) as mqtt:
The first `)` here breaks this

2023-11-03 00:49 UTC, turmoni commented on ooler_mqtt_bridge
> +                async with asyncio.TaskGroup() as tg:
Nine months later this isn't a problem any more.

2023-11-03 01:44 UTC, sredman commented on ooler_mqtt_bridge
> +import asyncio
```suggestion
```

2023-11-03 01:44 UTC, sredman commented on ooler_mqtt_bridge
> +                password=config["mqtt_password"]) if "mqtt_password" in config else None) as mqtt:
```suggestion
                password=config["mqtt_password"] if "mqtt_password" in config else None) as mqtt:
```

2023-11-03 01:46 UTC, sredman commented
> Thanks for the rebase, and sorry for taking a while to respond! I've now got this code running on my setup to verify it, just two comments:
> 
>     * The double import of asyncio
> 
>     * The extra `)` breaking the syntax
> 

That was a sloppy merge on my behalf, thanks for catching those.

2023-11-03 20:30 UTC, turmoni approved these changes

2023-11-03 20:30 UTC, merged